export const actions = {
    ADD_NEW_NOTE: "ADD_NEW_NOTE",
    SET_USERNAME: "SET_USERNAME",
    REMOVE_USERNAME: "REMOVE_USERNAME",
    ON_SEARCH_NOTE: "ON_SEARCH_NOTE",
    ON_DELETE_NOTE: "ON_DELETE_NOTE",
  };