const pokemonProducts = [
    {
        "id": "BRS TG17",
        "name": "Mimikyu VMAX",
        "price": "€17.00",
        "expansion": "ASTRI LUCENTI",
        "grade": "Secret Rare",
        "image": "./images//image_1.jpg",
    },
    {
        "id": "BRS 178",
        "name": "Ambizione di Camilla",
        "price": "€10.00",
        "expansion": "ASTRI LUCENTI",
        "grade": "Secret Rare",
        "image": "./images//image_2.jpg",
    },
    {
        "id": "BRS 018",
        "name": "Charizard V ASTRO",
        "price": "€20.00",
        "expansion": "ASTRI LUCENTI",
        "grade": "Ultra Rare",
        "image": "./images//image_3.jpg",
    },
    {
        "id": "LOR 212",
        "name": "Giratina V ASTRO",
        "price": "€60.00",
        "expansion": "ORIGINE PERDUTA",
        "grade": "Secret Rare",
        "image": "./images//image_4.jpg",
    },
    {
        "id": "LOR 201",
        "name": "Giratina V ASTRO",
        "price": "€50.00",
        "expansion": "ORIGINE PERDUTA",
        "grade": "Secret Rare",
        "image": "./images//image_5.jpg",
    },
    {
        "id": "LOR TG15",
        "name": "Centiskorch VMAX",
        "price": "€18.00",
        "expansion": "ORIGINE PERDUTA",
        "grade": "Ultra Rare",
        "image": "./images//image_6.jpg",
    },
    {
        "id": "ASR 209",
        "name": "Samurott di Hisui V ASTRO",
        "price": "€30.00",
        "expansion": "LUCENTEZZA SIDERALE",
        "grade": "Secret Rare",
        "image": "./images//image_7.jpg",
    },
    {
        "id": "ASR TG19",
        "name": "Zapdos di Galar V",
        "price": "€18.00",
        "expansion": "LUCENTEZZA SIDERALE",
        "grade": "Ultra Rare",
        "image": "./images//image_8.jpg",
    },
    {
        "id": "ASR 169",
        "name": "Typhlosion di Hisui V",
        "price": "€15.00",
        "expansion": "LUCENTEZZA SIDERALE",
        "grade": "Ultra Rare",
        "image": "./images//image_9.jpg",
    },
    {
        "id": "EVS 180",
        "name": "Espeon V",
        "price": "€100.00",
        "expansion": "EVOLUZIONI ETEREE",
        "grade": "Ultra Rare",
        "image": "./images//image_10.jpg",
    },
    {
        "id": "EVS 191",
        "name": "Dragonite V",
        "price": "€20.00",
        "expansion": "EVOLUZIONI ETEREE",
        "grade": "Ultra Rare",
        "image": "./images//image_11.jpg",
    },
    {
        "id": "EVS 221",
        "name": "Profumina",
        "price": "€15.00",
        "expansion": "EVOLUZIONI ETEREE",
        "grade": "Secret Rare",
        "image": "./images//image_12.jpg",
    },
    {
        "id": "LOR TG27",
        "name": "Azzurra",
        "price": "€15.00",
        "expansion": "ORIGINE PERDUTA",
        "grade": "Ultra Rare",
        "image": "./images//image_13.jpg",
    },
    {
        "id": "ASR TG18",
        "name": "Calyrex Cavaliere Spettrale VMAX",
        "price": "€15.00",
        "expansion": "LUCENTEZZA SIDERALE",
        "grade": "Ultra Rare",
        "image": "./images//image_14.jpg",
    },
    {
        "id": "BRS TG13",
        "name": "Boltund V",
        "price": "€15.00",
        "expansion": "ASTRI LUCENTI",
        "grade": "Secret Rare",
        "image": "./images//image_15.jpg",
    },
    {
        "id": "ASR TG26",
        "name": "Melania",
        "price": "€12.50",
        "expansion": "LUCENTEZZA SIDERALE",
        "grade": "Ultra Rare",
        "image": "./images//image_16.jpg",
    },
    {
        "id": "LOR TG03",
        "name": "Charizard",
        "price": "€12.00",
        "expansion": "ORIGINE PERDUTA",
        "grade": "Holo Rare",
        "image": "./images//image_17.jpg",
    },
    {
        "id": "PGO 076",
        "name": "Dragonite V",
        "price": "€15.00",
        "expansion": "POKEMON GO",
        "grade": "Ultra Rare",
        "image": "./images//image_18.jpg",
        "type": "full-art",
    },
    {
        "id": "EVS 191",
        "name": "Dragonite V",
        "price": "€20.00",
        "expansion": "EVOLUZIONI ETEREE",
        "grade": "Ultra Rare",
        "image": "./images//image_19.jpg",
        "type": "full-art",
    },
    {
        "id": "LOR 182",
        "name": "Drapion V",
        "price": "€10.00",
        "expansion": "ORIGINE PERDUTA",
        "grade": "Ultra Rare",
        "image": "./images//image_20.jpg",
        "type": "full-art",
    },
    {
        "id": "LOR 172",
        "name": "Electrode di Hisui V",
        "price": "€10.00",
        "expansion": "ORIGINE PERDUTA",
        "grade": "Ultra Rare",
        "image": "./images//image_21.jpg",
        "type": "full-art",
    },
    {
        "id": "FST 254",
        "name": "Genesect V",
        "price": "€15.00",
        "expansion": "COLPO FUSIONE",
        "grade": "Ultra Rare",
        "image": "./images//image_22.jpg",
        "type": "full-art",
    },
    {
        "id": "ASR 176",
        "name": "Samurott di Hisui V",
        "price": "€8.50",
        "expansion": "LUCENTEZZA SIDERALE",
        "grade": "Ultra Rare",
        "image": "./images//image_23.jpg",
        "type": "full-art",
    }
]

export default pokemonProducts;